### ISSUE TITLE
Getting undefined values

### ISSUE THREAD

**Issue by KCreate** [Shikkic/gitbar#9] opened 2016-06-05 19:51 UTC
I'm getting some undefined values. Is it possible that this is caused by GitHub recently removing the streak display on user's profiles?

![screenshot 2016-06-05 at 21 49 26](https://cloud.githubusercontent.com/assets/1352680/15807829/773c27aa-2b67-11e6-8675-7fb0102672fe.jpg)

**Comment by Shikkic** [comment] 2016-06-05 20:27
Hey @KCreate!

Thanks for opening an issue. Unfortunately yes, Github made some changes to profiles that broke some of the functionality. 

I've been a bit busy lately but I've been pondering what to do about it. If people think it's still valuable to have streaks I have all the commit data to calculate it. 

Any thoughts?

**Comment by KCreate** [comment] 2016-06-05 20:47
How exactly would you calculate the current streak? And should private contributions be counted as well?

I'd be happy to help with anything related to making this working again!

**Comment by KCreate** [comment] 2016-06-06 11:56
I've just submitted a pull-request on the gh-scrape repo of yours.
Would be an honor to have this merged since this is the first time I contribute to something other people have did.

https://github.com/Shikkic/gh-scrape/pull/2

Best regards,
Leonard

**Comment by Shikkic** [comment] 2016-06-06 20:30
Hey man this looks really great. I'm still a bit tied up at work this morning/afternoon but I'll take a peak tonight. 

Thanks for getting involved and contributing, from what I can see it looks like you did an awesome job.

**Comment by KCreate** [comment] 2016-06-06 20:36
Thanks!

**Comment by joshuaobrien** [comment] 2017-09-13 07:18
@Shikkic I see that this is still an issue for the project. Are you open to PRs for it? 🙂

**Comment by KCreate** [comment] 2017-09-13 07:33
@tiget There already is a PR for this.

https://github.com/Shikkic/gh-scrape/pull/2

I haven't tested it in a long time so it might not work anymore. If it's still working I see nothing that speaks against a merge.

**Comment by joshuaobrien** [comment] 2017-09-13 07:45
@KCreate great. I saw that but was unsure of the status. Keen to see this merged.

**Comment by Shikkic** [comment] 2017-09-13 13:34
@tiget @KCreate looking into it now

**Comment by Shikkic** [comment] 2017-09-13 14:07
@tiget @KCreate PR is up to fix the issue using @KCreate's fixes to `gh-scrape` (Thanks for that btw!). Will merge once I can confirm it works for someone else.

**Comment by Shikkic** [comment] 2017-09-15 03:22
@tiget @KCreate Issue should be fixed for undefined values 👍

**Closed as completed by Shikkic** 2017-09-15 03:22 UTC

**Comment by joshuaobrien** [comment] 2017-09-15 05:50
Cheers 😎
